name: build_scala
on:
  push:
    branches:
      - "scala/"
  pull_request:
    branches:
      - "scala/"
jobs:
  build:
    runs-on: ubuntu-20.04
      container:
        image: osgeo/gdal:ubuntu-small-3.6.2
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        python: [ 3.8.10 ]
        spark: [ 3.3.1 ]
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: build scala with tests
        uses: ./.github/actions/scala_build
      # - name: upload artefacts
      #   uses: ./.github/actions/upload_artefacts